import { UserInterface } from './user.interface';

export const userMock: UserInterface[] = [
  {
    id: 1,
    firstname: 'Michael',
    lastname: 'Jackson',
    email: 'michael@email.com',
    phoneNumber: '+145698562231',
    password: 'password1',
  },
  {
    id: 2,
    firstname: 'John',
    lastname: 'Smith',
    age: 45,
    email: 'john@email.com',
    phoneNumber: '+145698562312',
    password: 'password1',
  },
  {
    id: 3,
    firstname: 'Alex',
    lastname: 'Jackson',
    email: 'alex@email.com',
    phoneNumber: '+145231562231',
    password: 'password1',
  },
  {
    id: 4,
    firstname: 'Tomas',
    lastname: 'Miller',
    email: 'tom@email.com',
    phoneNumber: '+145698123123',
    password: 'password1',
  },
  {
    id: 5,
    firstname: 'Angelina',
    lastname: 'Jolie',
    age: 29,
    email: 'algel@email.com',
    phoneNumber: '+145698562221',
    password: 'password1',
  },
  {
    id: 6,
    firstname: 'test',
    lastname: 'Yan',
    age: 21,
    email: 'test@gmail.com',
    phoneNumber: '+3744984654897',
    password: 'password1',
  },
];
